In [1]:
import sys
import numpy as np
import matplotlib

print("Python: ", sys.version)
print("Numpy:", np.__version__)
print("Matplotlib:", matplotlib.__version__)

Python:  3.12.2 (tags/v3.12.2:6abddd9, Feb  6 2024, 21:26:36) [MSC v.1937 64 bit (AMD64)]
Numpy: 1.26.4
Matplotlib: 3.8.3


In [2]:
# coding neurons
inputs = [1.2, 5.1, 2.1]
weights = [3.1, 2.1, 8.7]
bias = 3

output = inputs[0]*weights[0] + inputs[1]*weights[1] + inputs[2]*weights[2] + bias
print(output)

35.7


In [3]:
# 2nd Video


In [4]:
"""
Here, we are having 3 neurons and all the neurons are having same inputs
but the weights of each of the neurons are different and every neurons 
is having it's own biases.

"""
inputs = [1, 2, 3, 2.5]
weights1 = [0.2, 0.8, -0.5, 1.0]
weights2 = [0.5, -0.91, 0.26, -0.5]
weights3 = [-0.26, -0.27, 0.17, 0.87]

bias1 = 2
bias2 = 3
bias3 = 0.5

output = [inputs[0]*weights1[0] + inputs[1]*weights1[1] + inputs[2]*weights1[2] + inputs[3]*weights1[3] + bias1,
          inputs[0]*weights2[0] + inputs[1]*weights2[1] + inputs[2]*weights2[2] + inputs[3]*weights2[3] + bias2,
          inputs[0]*weights3[0] + inputs[1]*weights3[1] + inputs[2]*weights3[2] + inputs[3]*weights3[3] + bias3]
print(output)

[4.8, 1.21, 2.385]


In [5]:
# 3rd Video


In [6]:
inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

# Output of Current Layer
layer_outputs = []

"""
zip function is used to convert the given lists into a nested lists
weights, biases are zipped


First Iteration:

neuron_weights = [0.2, 0.8, -0.5, 1.0]
neuron_bias = 2
For the first neuron:
n_input = 1, weight = 0.2: neuron_output += 1 * 0.2
n_input = 2, weight = 0.8: neuron_output += 2 * 0.8
n_input = 3, weight = -0.5: neuron_output += 3 * (-0.5)
n_input = 2.5, weight = 1.0: neuron_output += 2.5 * 1.0
neuron_output += 2: Adding bias
neuron_output = 0.2 + 1.6 - 1.5 + 2.5 + 2 = 5.8
layer_outputs = [5.8]


Second Iteration:

neuron_weights = [0.5, -0.91, 0.26, -0.5]
neuron_bias = 3
For the second neuron:
n_input = 1, weight = 0.5: neuron_output += 1 * 0.5
n_input = 2, weight = -0.91: neuron_output += 2 * (-0.91)
n_input = 3, weight = 0.26: neuron_output += 3 * 0.26
n_input = 2.5, weight = -0.5: neuron_output += 2.5 * (-0.5)
neuron_output += 3: Adding bias
neuron_output = 0.5 - 1.82 + 0.78 - 1.25 + 3 = 1.26
layer_outputs = [5.8, 1.26]


Third Iteration:

neuron_weights = [-0.26, -0.27, 0.17, 0.87]
neuron_bias = 0.5
For the third neuron:
n_input = 1, weight = -0.26: neuron_output += 1 * (-0.26)
n_input = 2, weight = -0.27: neuron_output += 2 * (-0.27)
n_input = 3, weight = 0.17: neuron_output += 3 * 0.17
n_input = 2.5, weight = 0.87: neuron_output += 2.5 * 0.87
neuron_output += 0.5: Adding bias
neuron_output = -0.26 - 0.54 + 0.51 + 2.175 + 0.5 = 2.385
layer_outputs = [5.8, 1.26, 2.385]


"""

for neuron_weights, neuron_bias in zip(weights, biases):
    neuron_output = 0 # output of given neuron
    for n_input, weight in zip(inputs, neuron_weights):
        neuron_output += n_input*weight
    neuron_output += neuron_bias
    layer_outputs.append(neuron_output)

print(layer_outputs)

[4.8, 1.21, 2.385]


In [7]:
# Tensor is an object that is used to store array.

# dot Product

inputs = [1, 2, 3, 2.5]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

# dot product
output = np.dot(weights, inputs) + biases
print(output)

[4.8   1.21  2.385]


In [8]:
# 4th Video


In [12]:
# Batches(collection of i/p) are used to plot the best fit line.
# the more the batch size the less time required for plotting best fit line.
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

# dot product
# converting the weights list to numpy array and transposing it.
output = np.dot(inputs, np.array(weights).T) + biases
print(output)

[[ 4.8    1.21   2.385]
 [ 8.9   -1.81   0.2  ]
 [ 1.41   1.051  0.026]]


In [14]:
# Batches(collection of i/p) are used to plot the best fit line.
# the more the batch size the less time required for plotting best fit line.
inputs = [[1, 2, 3, 2.5],
          [2.0, 5.0, -1.0, 2.0],
          [-1.5, 2.7, 3.3, -0.8]]

weights = [[0.2, 0.8, -0.5, 1.0],
           [0.5, -0.91, 0.26, -0.5],
            [-0.26, -0.27, 0.17, 0.87]]

biases = [2, 3, 0.5]

weights2 = [[0.1, -0.14, 0.5],
           [-0.5, 0.12, -0.33],
            [-0.44, 0.73, -0.13]]

biases2 = [-1, 2, -0.5]

# dot product
# converting the weights list to numpy array and transposing it.
layer1_outputs = np.dot(inputs, np.array(weights).T) + biases

layer2_outputs = np.dot(layer1_outputs, np.array(weights2).T) + biases2

print(layer2_outputs)

[[ 0.5031  -1.04185 -2.03875]
 [ 0.2434  -2.7332  -5.7633 ]
 [-0.99314  1.41254 -0.35655]]


In [20]:
# the more the batch size the less time required for plotting best fit line.
# input data.
X = [[1, 2, 3, 2.5],
     [2.0, 5.0, -1.0, 2.0],
     [-1.5, 2.7, 3.3, -0.8]]



class Layer_Dense:
    def __init__(self, n_inputs, n_neurons):
        self.weights = 0.10 * np.random.randn(n_inputs, n_neurons)
        self.biases = np.zeros((1, n_neurons))
    def forward(self, inputs):
        self.outputs = np.dot(inputs, self.weights) + self.biases

layer1 = Layer_Dense(4, 5)
layer2 = Layer_Dense(5, 2)

layer1.forward(X)
# print(layer1.outputs)

layer2.forward(layer1.outputs)
print(layer2.outputs)

[[ 0.02295661 -0.03046261]
 [ 0.14088957 -0.02896866]
 [ 0.00633358 -0.00087365]]


In [21]:
# 5th Video
